---
services:
  homeassistant:
    container_name: wifi-ssid-monitor-dev
    image: ha-dev-base:latest
    volumes:
      # Mount the whole project so the DevContainer workspace works
      - ..:/workspaces/ha-wifi-ssid-monitor
      # Mount your local dev config
      - ./.devconfig:/config
      # IMPORTANT: Use a relative path from the
      #  project root inside the container
      # This ensures HA sees your code as an integration
      - ../custom_components/wifi_ssid_monitor:/config/custom_components/wifi_ssid_monitor:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - SUPERVISOR_TOKEN=mock_dev_token
    depends_on:
      - supervisor

  # Mock service to simulate Supervisor API as host will not pass thru WiFi
  supervisor:
    image: python:3.11-slim
    container_name: supervisor_mock
    volumes:
      - ./mock_supervisor.py:/mock_supervisor.py:ro
    command: python /mock_supervisor.py
